spring.application.name=SpringBoot-Value


app.name=Springboot Core Practice
app.version=1.0
app.author=David

student.name=Alex
student.age=22

number.list=10,20,30,40,50

app.languages=Java,Python,Go,JavaScript